# Dependencies
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty

# Setup
title: Chaitanya Jadhav
tagline: "A Jekyll theme"
description: "Notes about art, football, tech and life"
url: indicium15.github.io
baseurl: /
emailme: chaitanya.jadhav15@hotmail.com

author:
  name: "Chaitanya Jadhav"

plugins: [jekyll-paginate]
paginate: 5

# Custom vars
version: 2.1.0

github:
  repo: https://github.com/indicium15/indicium15.github.io

